### ISSUE TITLE
Extra Feature - Bluetooth

### ISSUE THREAD

**Issue by sn1p3r46** [monobox/aggregator#1]
Could be cool to add an extra feature. What about a Bluetooth module in order to stream music from a smartphone? Does it fit with concept behind this project? :) 

Some code snippets are here! :) 
If I find the time this week I'll test it on my RPi.

http://marcyoung.us/post/raspberry-pi-automated-bluetooth-audio-player/

**Comment by oxullo** [comment]
We had bluetooth streaming and OSX Airplay compatibility running pretty fine, but we decided to go drastically minimal removing them.
Our last mantra is: this device has 1 physical control and it does only 1 thing: playing radios.
Thanks for the suggestion, though!
